name: ESLint CI

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        id: eslint
        run: npm run lint

      - name: Prevent merge if ESLint fails
        if: ${{ job.status != 'success' }}
        run: |
          echo "ESLint check failed. Cannot merge pull request."
          exit 1
